// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Pipeline.API.Models
{
    public partial class Category
    {
        public Category()
        {
        }

        public Guid CategoryId { get; set; }
        public string CategoriesName { get; set; }
        public Guid CategoriesParent { get; set; }
        public string CategoriesNotes { get; set; }
        public int CategoriesSortOrder { get; set; }
        public string CategoriesDescription { get; set; }
        public DateTime TimeFirst { get; set; }
        public DateTime TimeLast { get; set; }
    }
}