// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Pipeline.Model.Models
{
    public class Category :Auditable
    {
        public Guid CategoryId { get; set; }
        public string CategoriesName { get; set; }
        public Guid CategoriesParent { get; set; }
        public string CategoriesNotes { get; set; }
        public int CategoriesSortOrder { get; set; }
        public string CategoriesDescription { get; set; }
       
    }
}