// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Pipeline.Model.Models
{
    public partial class Product
    {
        public Product()
        {
        }

        public Guid ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductsDescription { get; set; }
        public string ProductsNotes { get; set; }
        public Guid ProductUnitTypesId { get; set; }
        public string ProductsAccuracy { get; set; }
        public int ProductsRounding { get; set; }
        public decimal ProductsWaste { get; set; }
        public bool ProductsSupplementalToBid { get; set; }
        public decimal ProductsProjectedCost { get; set; }
        public bool ProductsIsArchived { get; set; }
        public DateTime TimeFirst { get; set; }
        public DateTime TimeLast { get; set; }


    }
}